# Generated by Django 3.2.16 on 2025-01-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ('departure_time',), 'verbose_name': 'Рейс', 'verbose_name_plural': 'Рейсы'},
        ),
        migrations.AddField(
            model_name='flight',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Отображено'),
        ),
    ]
