# Generated by Django 3.2.16 on 2025-01-26 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20250126_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flightreservation',
            options={'ordering': ('-created_at',), 'verbose_name': 'Бронь рейса', 'verbose_name_plural': 'Брони рейса'},
        ),
    ]
